version: "3"
services:
  redis:
    image: redis
    command: redis-server

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=outline
      - PGDATA=/pgdata
    volumes:
      - ./data/postgresql:/pgdata

  outline:
    image: outline:master
    command: '/opt/outline/docker-start'
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/outline
      - REDIS_URL=redis://redis:6379
      - FORCE_HTTPS=false
      - ENABLE_UPDATES=false
    depends_on:
      - postgres
      - redis
